# Generated by Django 4.2.1 on 2023-05-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('student_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('level', models.PositiveSmallIntegerField()),
                ('status', models.BooleanField()),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('IS', 'Information System'), ('IT', 'Information Technology'), ('AI', 'Aritificial Inteligence'), ('DS', 'Descision Support')], max_length=10, null=True)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
            ],
        ),
    ]
