# Generated by Django 4.1.7 on 2023-05-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CS', 'CS'), ('IS', 'IS'), ('IT', 'IT'), ('AI', 'AI'), ('DS', 'DS')], max_length=10, null=True),
        ),
    ]
