# Generated by Django 4.2.1 on 2023-05-29 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_admin_accounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_accounts',
        ),
    ]
